name: Vite on Pull Request

on:
  pull_request:
    paths:
      - .github/workflows/**
      - components/**
      - test/**
      - package.json
      - yarn.lock
      - vitest.config.ts

jobs:
  testing:
    uses: ./.github/workflows/action_vite_testing.yml

  linting:
    uses: ./.github/workflows/action_vite_linting.yml

  sonar:
    uses: ./.github/workflows/action_sonarcloud.yml
    needs: [ testing ]
    secrets:
      github: ${{ secrets.GITHUB_TOKEN }}
      sonar: ${{ secrets.SONAR_TOKEN }}