name: Vite on Pull Request

on:
  pull_request:
    paths:
      - .github/workflows/vite_on_release.yml
      - components/**
      - test/**
      - package.json
      - yarn.lock
      - vitest.config.ts

jobs:
  testing:
    uses: ./.github/workflows/action_vite_testing.yml

  linting:
    uses: ./.github/workflows/action_vite_linting.yml